print("Hello student, please enter the following information")
a=input("First name: ")
b=input("last name: ")
c=input("Age: ")
d=input("GPA: ")
e=input("Major: ")
f=input("address: ")
print("\n")
print("This students name is",(a),(b),", they are",(c),"years old ,","They have a GPA score of",(d),",")
print("they have a major in",(e),"and their address is",(f),".")
print("\n")
input("Please type STOP to end the program:")
