print("Welcome to the trapezoid area calculator")
print("Please enter the dimensions of your trapeziod: ")
x1 = float(input("length of top side: "))
x2 = float(input("length of bottom side: "))
x3 = float(input("height of the trapezoid: "))
y = (((x1 + x2) * x3) / 2 )
print("The area of your trapezoid is",y,)
input("Please type STOP to end the program: ")